-- Create the ftes table
CREATE TABLE IF NOT EXISTS ftes (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  name       text NOT NULL
);

-- Enable RLS and add read policy (matches tasks pattern)
ALTER TABLE ftes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON ftes FOR SELECT USING (true);

-- Grant access to PostgREST roles
GRANT ALL ON ftes TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE ftes_id_seq TO anon, authenticated;

-- Add requestor and assignee FK columns to tasks
ALTER TABLE tasks
  ADD COLUMN requestor bigint REFERENCES ftes(id),
  ADD COLUMN assignee  bigint REFERENCES ftes(id);
